### ISSUE TITLE
Cannot compile exe with pyinstaller (Windows 7)

### ISSUE THREAD

**Issue by KAILO776** [TomSchimansky/CustomTkinter#113]
When using pyinstaller, pyinstaller cannot package customtkinter file
![2022-05-25_18h49_39](https://user-images.githubusercontent.com/106268970/170326131-fa8c387b-8d3a-4318-9a7f-87d9a1eb4a39.png)
s

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

**Comment by KAILO776** [comment]
Thank you for linking the help.

I have followed the steps, but still receive errors, could i post them here?
![2022-05-25_19h49_32](https://user-images.githubusercontent.com/106268970/170329946-f752b89e-c640-48b8-82e7-144e6bc49c07.png)

Thank you,
Kind regards

**Comment by KAILO776** [comment]
It does not, ive built numerous Tkinter apps with no issues.
i however really liked the customtkinter module so i tried using it for my latest app.

I found an answer on stackOverflow post: https://stackoverflow.com/questions/60315287/main-pyinstallerimporterror-failed-to-load-dynlib-dll-shcore

stating that [SetProcessDpiAwareness] is not compatible with windows versions older than 8.1, could this be the issue?

**Comment by TomSchimansky** [comment]
Ok, I use `windll.shcore.SetProcessDpiAwareness(2)` to make the process DPI aware. You can take a look at the code: https://github.com/TomSchimansky/CustomTkinter/blob/aa8c96a2c4f7f072c50f02ff4f84772f90ca1875/customtkinter/scaling_tracker.py#L134
You can try to set this flag at the beginning of your program:
```python
customtkinter.ScalingTracker.deactivate_automatic_dpi_awareness = True
```
Then the program will not be scaled on HighDPI displays (It will be blurry).
Or you can download the repository and delete the line or replace them with [SetProcessDPIAware](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware) if thetas working. Or you create an if statement and check if you are on Windows 8.1 or higher before using shcore. I think I will do it this way too in the next release.

**Comment by KAILO776** [comment]
Apologies i'm not too familiar with using external classes

i'm receiving error: "Cannot find reference 'ScalingTracker' in '__init__.py' "
i've tried adding "from customtkinter import *" with no change

**Comment by TomSchimansky** [comment]
Are you using the latest version 4.1.0?
It should work like this:
```python
import customtkinter

customtkinter.ScalingTracker.deactivate_automatic_dpi_awareness = True
```
Otherwise maybe you can post your code...

**Comment by KAILO776** [comment]
Correct yes
version:
```
C:\Python\Disease_identifier>pip install customtkinter update
Requirement already satisfied: customtkinter in c:\users\kailo\appdata\local\programs\python\python38-32\lib\site-packages (4.1.0)
```

Code:
```
import customtkinter
from customtkinter import *

customtkinter.ScalingTracker.deactivate_automatic_dpi_awareness = True
```

**Comment by KAILO776** [comment]
i'm trying to make an application, so i can give this to someone who doesn't have python, so they can run it like any other app.

**Comment by sennewood** [comment]
Could you post the whole `pyinstaller` command you tried?

**Comment by KAILO776** [comment]
Command:
 `pyinstaller Diagnoser_App.py --noconfirm --onedir --add-data "c:\users\kailo\appdata\local\programs\python\python38-32\lib\site-packages/customtkinter;customtkinter`

**Comment by TomSchimansky** [comment]
You can also try to do:
```python
customtkinter.deactivate_automatic_dpi_awareness()
```

**Comment by KAILO776** [comment]
Alright, I've created a new virtual environment and double checked version 4.1.0 is installed.

Using:

```
customtkinter.deactivate_automatic_dpi_awareness()
customtkinter.ScalingTracker.deactivate_automatic_dpi_awareness = True
```
both individually and together, and receive this error:

```
Traceback (most recent call last):
  File "C:/Python/venv-Diagnoser/Diagnoser_App.py", line 429, in <module>
    root = customtkinter.CTk()
  File "C:\Python\venv-Diagnoser\lib\site-packages\customtkinter\windows\ctk_tk.py", line 31, in __init__
    ScalingTracker.add_widget(self.set_scaling, self)
  File "C:\Python\venv-Diagnoser\lib\site-packages\customtkinter\scaling_tracker.py", line 94, in add_widget
    cls.window_dpi_scaling_dict[window_root] = cls.get_window_dpi_scaling(window_root)
  File "C:\Python\venv-Diagnoser\lib\site-packages\customtkinter\scaling_tracker.py", line 155, in get_window_dpi_scaling
    windll.shcore.GetDpiForMonitor(monitor_handle, DPI_type, pointer(x_dpi), pointer(y_dpi))
  File "C:\Users\KAILO\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\KAILO\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'shcore' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by TomSchimansky** [comment]
OK, I know what's the problem. It will be fixed in the next version.

**Comment by KAILO776** [comment]
Okay great, 
Is there something i can do just to be able to convert  this one? and then i can hold off of using CustomTkinter until the next version is released

**Comment by TomSchimansky** [comment]
I will probably release the next version tonight 😅.

**Comment by KAILO776** [comment]
Ok great!
Thank you, i really appreciate the effort.
i will revert back if the new version still has the issue.

**Comment by KAILO776** [comment]
Would like to confirm whether the DPI issue has been fixed? still can't run the code on Win7.

**Comment by TomSchimansky** [comment]
I released version 4.2.0, and this should be fixed now. Maybe you can try it again.

**Comment by Think-IT-think-gui** [comment]
I think you switch to window 8 or higher, it could be that some packages just don't work with anything below python 3

**Comment by KAILO776** [comment]
I can run my code now, but unfortunately i still get the last error i posted, even with disabling dpi awareness

**Comment by TomSchimansky** [comment]
I don't know what's the problem then, if you want to package it, you can try to download the repository and delete all lines where I do `from ctypes import windll`. Otherwise I would say packaging for Windows 7 is not supported by default. You could also try to exclude windll.shcore from the packaging...
