### ISSUE TITLE
ComboBox Disabled Color issue

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#161]
When I set combobox state to **DISABLED** then the bg color of the text changes to **white** (see the screenshot):

![Akascape_Screenshots](https://user-images.githubusercontent.com/89206401/172362199-53cad4ea-78e3-4c6f-92a5-ff1eeb0fc253.png)
I used the basic code without any color parameter:
```python
Combobox1=customtkinter.CTkComboBox(master=window, height=40, width=150,
                                     values=["Some Text"])
Combobox1.configure(state=tkinter.DISABLED)
```
I think this is a bug, please try to fix this!

**Comment by TomSchimansky** [comment]
I think you are using an old version please try upgrading, this was already fixed: https://github.com/TomSchimansky/CustomTkinter/issues/85

**Comment by TomSchimansky** [comment]
This should be now fixed with version 4.4.0.

**Comment by Akascape** [comment]
I have updated customtkinter to 4.4.0 but still getting this:
![Akascape's screenshots](https://user-images.githubusercontent.com/89206401/173885142-0433a21e-daf5-49dd-b38f-90941d0eafd9.png)

**Comment by felipetesc** [comment]
Hello [Akascape](https://github.com/Akascape). It looks like the label bg isn't being passed from the combobox to the label. Can you post your sample code, so, I can test here to see if I can help ?

**Comment by felipetesc** [comment]
> Try this code
> 
> ```python
> import tkinter
> import tkinter.ttk as ttk
> import customtkinter
> 
> app = customtkinter.CTk()
> app.title('Test OptionMenu ComboBox.py')
> app.geometry('300x100')
> 
> def disable():
>     if checkbox.get()==1:
>         combobox.configure(state=tkinter.DISABLED)
>     else:
>         combobox.configure(state=tkinter.NORMAL)
> 
> countries = ['A', 'B', 'C']
> 
> combobox = customtkinter.CTkComboBox(app, values=countries)
> combobox.pack(pady=10)
> checkbox= customtkinter.CTkCheckBox(app,text="Disable", command=disable)
> checkbox.pack(pady=10)
> app.mainloop()
> ```

I will run it here. Thanks.

**Comment by Akascape** [comment]
In my system:

Normal
![Screenshot 2022-06-15 225819](https://user-images.githubusercontent.com/89206401/173889294-4479bda2-30f1-4e46-9a70-609cc15a8388.png)
Disabled
![Screenshot 2022-06-15 225830](https://user-images.githubusercontent.com/89206401/173889311-9b42e8a9-b4dc-4ba5-a144-ea00fd52f2db.png)

**Comment by felipetesc** [comment]
> In my system:
> 
> Normal ![Screenshot 2022-06-15 225819](https://user-images.githubusercontent.com/89206401/173889294-4479bda2-30f1-4e46-9a70-609cc15a8388.png) Disabled ![Screenshot 2022-06-15 225830](https://user-images.githubusercontent.com/89206401/173889311-9b42e8a9-b4dc-4ba5-a144-ea00fd52f2db.png)

![combobox_disabled](https://user-images.githubusercontent.com/2336812/173890163-29952dba-760b-47ab-abbf-a060758c4189.gif)

**Comment by felipetesc** [comment]
Hi, I commented the line 186, containing:
```python 
#self.entry.configure(state=self.state) 
``` 
and I acquired the following result:
![combobox_disabled_fix](https://user-images.githubusercontent.com/2336812/173894842-b0647ba4-ed16-4cd2-969a-771c87017a37.gif)

If you delete your pip package, clone customtkinter repository and call customtkinter like this:
```python 
import sys
sys.path.append("path_to_ctk/CustomTkinter/")
```

Where **_path_to_ctk_** is the path to the cloned CustomTkinter.

Then, inside CustomTkinter/custom tkinter/widgets/ctk combobox.py comment the line 186. It will be nice if you can test.

**Comment by TomSchimansky** [comment]
I will have a look at this...

**Comment by felipetesc** [comment]
> I will have a look at this...

If the line 169 is like this:

```python
self.entry.configure(fg=(ThemeManager.single_color(self.text_color_disabled, self._appearance_mode)))
```
all the background color changes to white.

But if change the color to red only the label color changes:

```python
self.entry.configure(fg="red")
self.canvas.itemconfig("dropdown_arrow", fill=ThemeManager.single_color(self.text_color_disabled,self._appearance_mode))
```

**Comment by felipetesc** [comment]
> > I will have a look at this...
> 
> If the line 169 is like this:
> 
> ```python
> self.entry.configure(fg=(ThemeManager.single_color(self.text_color_disabled, self._appearance_mode)))
> ```
> 
> all the background color changes to white.
> 
> But if change the color to red only the label color changes:
> 
> ```python
> self.entry.configure(fg="red")
> self.canvas.itemconfig("dropdown_arrow", fill=ThemeManager.single_color(self.text_color_disabled,self._appearance_mode))
> ```

I'm using Linux
