### ISSUE TITLE
CTkToplevel not displaying

### ISSUE THREAD

**Issue by legopitstop** [TomSchimansky/CustomTkinter#469]
CTkToplevel is not displaying when the resizeable method is used.

customtkinter: `4.6.3`
IOS: `Windows 10`

**Steps To Reproduce**
1. Run the below code in a python file.
2. Click the button in the main window
3. Nothing happens
4. Remove the `resizable` method in the toplevel function.
5. The toplevel window properly  displays

**Observed Results**
- Console does not return any errors.
- Changing the values inside the resizeable method does nothing.
- Works fine on MacOS

Code:
```python
from customtkinter import CTk, CTkToplevel, CTkButton

root = CTk()
root.resizable(False, False)

def toplevel():
    print('OPEN')
    top = CTkToplevel(root)
    top.resizable(False, False) # Prevents window from opening
    button = CTkButton(top, command=top.destroy)
    button.pack(padx=20, pady=20)

button = CTkButton(root, command=toplevel)
button.pack(padx=20, pady=20)
root.mainloop()
```

**Comment by pourhakimi** [comment]
I ran the code you posted, it works fine (macOS). 
Maybe try it this way, using a class with ck.CTk inheritance:
```
import customtkinter as ck

ck.set_appearance_mode("dark")  # Options: light, dark, auto
ck.set_default_color_theme("dark-blue")  # Options: blue, dark-blue, green

class App(ck.CTk):
    def __init__(self, *args, fg_color="default_theme", **kwargs):
        super().__init__(*args, fg_color=fg_color, **kwargs)
        self.resizable(False, False)
        self.button = ck.CTkButton(self, command=self.toplevel)
        self.button.pack(padx=20, pady=20)

    def toplevel(self):
        print("OPEN")
        top = ck.CTkToplevel(self)
        top.resizable(False, False)  # Prevents window from opening
        button = ck.CTkButton(top, command=top.destroy)
        button.pack(padx=20, pady=20)

    def on_closing(self, event=0):
        self.destroy()
        exit(0)

    def start(self):
        self.mainloop()


if __name__ == "__main__":
    app = App()
    app.start()

```

**Comment by legopitstop** [comment]
The ck.CTk inheritance still didnt work. Must be a windows 10 issue.

**Comment by TomSchimansky** [comment]
Its only a Windows 10 issue, I fixed it, and it will build a new release version soon.

**Comment by Corporation001** [comment]
Sorry,I'm on Windows 11,but the problem still exist even though the customtkinter version have up to date...

> Its only a Windows 10 issue, I fixed it, and it will build a new release version soon.

**Comment by TomSchimansky** [comment]
Its a problem for all Windows versions, and I didn't upload a new version yet, but I will do it maybe tomorrow when some other changes are also ready.

**Comment by Corporation001** [comment]
> Its a problem for all Windows versions, and I didn't upload a new version yet, but I will do it maybe tomorrow when some other changes are also ready.

Thank you!

**Comment by yuseffathi** [comment]
When the fix will be updated,please?

**Comment by OffApparition** [comment]
Just here to say that the issue still persists.
The standard tkinter.Toplevel() works fine but customtkinter.CTkToplevel() still doesn't work with the resizable parameters.

**Comment by TomSchimansky** [comment]
Should be fixed with version 5.0.0.
