### ISSUE TITLE
Bug when changing image on a button using configure

### ISSUE THREAD

**Issue by clear-code-projects** [TomSchimansky/CustomTkinter#807]
There is a bug that prevents images on buttons being updated when using configure

```
import tkinter as tk
import customtkinter
from PIL import Image

def update_button_image():
	button.configure(fg_color = 'red') # does work
	button.configure(image = image_chat) # does not work

app = customtkinter.CTk()
app.geometry('200x200')

# image 
image_home = customtkinter.CTkImage(light_image = Image.open('home_dark.png'), dark_image = Image.open('home_light.png'))
image_chat = customtkinter.CTkImage(light_image = Image.open('chat_dark.png'), dark_image = Image.open('chat_light.png'))

button = customtkinter.CTkButton(app, text = 'change image', image = image_home, command = update_button_image)
button.pack(expand = True)
app.mainloop()
```

**Comment by TomSchimansky** [comment]
fixed with version 5.0.3.

**Comment by ringo70** [comment]
Changing the image still doesn't work. Not even when I upgraded to version 5.1.2. Changing the fg_color does work.

**Comment by IshanJ25** [comment]
+1

**Comment by cwhaley112** [comment]
This issue should be re-opened. CTkButton.configure(image) still does not change the image in the newest version. I've noticed that the image only appears after I click a button (doesn't have to be the one I changed).

**Comment by cwhaley112** [comment]
> This issue should be re-opened. CTkButton.configure(image) still does not change the image in the newest version. I've noticed that the image only appears after I click a button (doesn't have to be the one I changed).

Fixed by calling `self._draw()` after `self.configure(image)`. The fix in version 5.0.3 removed the `require_redraw=True` line from `self.configure(image)`. I think this should be re-added.

**Comment by franciscobortolanza** [comment]
Hello, I landed here when I was looking for this same problem. I'm not sure I understand very well what you're having trouble with, but my problem was that I couldn't update my button image using a function that it called.

If this is your problem, here is the solution I found:

I took the .place from the same line as the button.

And now my button's .configure method works, and so when my function is called, I can change my button's image using the .configure(image) method.

My code: 

  img_show_password = CTkImage(light_image=Image.open('./images/icon_show_password.png'), size=(31/1.3, 31/1.3))
  img_hide_password = CTkImage(light_image=Image.open('./images/icon_hide_password.png'), size=(31/1.3, 31/1.3))
  
  
  def show_password():
      if get_senha.cget('show') == '*':
          get_senha.configure(show= '')
          my_button.configure(image=img_show_password)
      else:
          get_senha.configure(show= '*')
          my_button.configure(image=img_hide_password)

  
  my_button = CTkButton(frame_login, text='', command=show_password, image=img_hide_password,
                              width=30, height=30, fg_color='#0098FE')
  
  my_button.place(x= 500, y=355)
